### ISSUE TITLE
Collision Crashes

### ISSUE THREAD

**Issue by Ne0Fox** [Wano-k/RPG-Paper-Maker#76]
So I put collision on an object and set the object to follow the player, but every time the collision box of the object touches the collision box of the player it crashes.
This issue also happens when The object collides with anything else with a collision box (a mountain for example).
the only work around for this that I know currently is Disabling collision boxes with though as soon as the player interacts with the object, but the it can go though walls and that's not what I'm going for...

Is there a way to solve this? because it would be cool for objects to follow the player like in deltarune (just an example because I really love that game) 

Also is there a way to make loop music better?

**Comment by Wano-k** [comment]
Probably too old and maybe already solved with lot of collisions improvements since then, could not reproduce. Would need to have the error message to correct it now.
