### ISSUE TITLE
Mac OS Download looks like it downloading a .exe file rather than a .app file

### ISSUE THREAD

**Issue by adxsoft** [Wano-k/RPG-Paper-Maker#78]
I downloaded the _RPG-Paper-Maker.app_  which let me choose the latest version of RPM however when it was downloadingit looks like it is downloading the **windows** version of RPG Paper Maker 1.9.2. The RPG-Paper-Maker app just hangs with the message 'Finishing'

![mac os downloading message](https://user-images.githubusercontent.com/24862237/146659067-5edd991b-83b6-471f-a2ca-60b7663a61f2.png)

**Comment by adxsoft** [comment]
PS I was using Mac OS High Sierra

**Comment by BetcoinContact** [comment]
In my case he created a folder: Engine / content / osx, inside there is the program, instead of putting with the applications played in the place where you saved the installer.

**Comment by Wano-k** [comment]
Should be solved when 3.0.0 will be out. Please re-open if any issue again with new version.
