### ISSUE TITLE
Your website is down

### ISSUE THREAD

**Issue by HammyHavoc** [Wano-k/RPG-Paper-Maker#82]
It's down: http://rpg-paper-maker.com/

Did HackerNews hug it to death?

**Comment by Wano-k** [comment]
Yes it looks like HackerNews is related to this but I don't get why. Anyway I was thinking about reworking the website very soon, the server host is having a lot of issues.

**Comment by HammyHavoc** [comment]
You could do a static GitHub Pages hosted website, I'm sure the free tier
would be more than adequate. :- ) Very reliable. The free plan on
CloudFlare for CloudFlare Pages is another good one.

**Comment by Wano-k** [comment]
Server was now changed. Hope it'll get better. :)
