### ISSUE TITLE
Just one question about RPG Paper Maker

### ISSUE THREAD

**Issue by Fulgurance** [Wano-k/RPG-Paper-Maker#83]
Hello, sorry if I post that in the RPG Paper Maker C++ version, I would liked just to be sure you seen my message. I have a question about the old Ruby version of RPG Paper maker, about the Texture. Because I'm using Gosu as well with OpenGL, but Gosu Image default class can't tiled an image. How you done that ?

**Comment by EgyLynx** [comment]
different series... i think...

**Comment by Wano-k** [comment]
Sorry for the late reply, but you can check all the source code of the ruby version there: [https://github.com/Wano-k/Gosu-Game-Engine-RUBY](https://github.com/Wano-k/Gosu-Game-Engine-RUBY), I honestly don't remember how I did since it was so long time ago!
