### ISSUE TITLE
How to change object State in Script? How to use Event Commands?

### ISSUE THREAD

**Issue by LucasMW** [Wano-k/RPG-Paper-Maker#93]
What's the correct way to change the state of an object via script?
Couldn't find an example in documentation.

See picture:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/8429832/215521338-bcccda17-55bb-448b-94d1-e99bb5f0f4ca.png">

For what I've tested if I do,

```
$object.system.states[0] = $object.system.states[2];
$object.changeState();
```
The object will change to state index 2. Does every time I want to change state of an object in a script I have to re-order the $object.system.states array? Is this the intended api?
What's the intende api? 
I am looking for just changing the index of the current state; Something like `$object.setState(1);` or `$object.currentStateIndex = 3; `
I couldn't find also how to call the change state event command on the script. 
How can I do it?

Thanks in advance!

**Comment by Wano-k** [comment]
Hello! Well, the object system can be more complicated than expected because of map portions where you need to register every state change in the map for saves purposes. If you check EventCommand/ChangeState, it looks like something like that:

```
let MY_NEW_ID = ...;
let portion = $object.position.getGlobalPortion();
let portionDatas = Game.current.getPortionDatas(Scene.Map.current.id, portion);
let indexState = portionDatas.si.indexOf($object.id);
if (indexState === -1) {
    indexState = portionDatas.si.length;
    portionDatas.si.push($object.id);
    portionDatas.s.push([1]);
}
EventCommand.ChangeState.removeAll(portionDatas, indexState);
EventCommand.ChangeState.addState(portionDatas, indexState, MY_NEW_ID);
$object.changeState();
```

I think this should be a method directly included in the MapObject class. Hope it helps!

**Comment by LucasMW** [comment]
I've tried to create a function to call your code but it gives this error. 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/8429832/215744007-3bcdd572-117b-439c-808f-25bdd03c2513.png">

It crashes the whole game.

This was the code:

```
function changeObject(MY_NEW_ID) {
let portion = $object.position.getGlobalPortion();
let portionDatas = Game.current.getPortionDatas(Scene.Map.current.id, portion);
let indexState = portionDatas.si.indexOf($object.id);
if (indexState === -1) {
    indexState = portionDatas.si.length;
    portionDatas.si.push($object.id);
    portionDatas.s.push([1]);
}
EventCommand.ChangeState.removeAll(portionDatas, indexState);
EventCommand.ChangeState.addState(portionDatas, indexState, MY_NEW_ID);
$object.changeState();
}
```

and I tried calling it like

`changeObject(22);`

I'm using RPG Paper Maker v.2.0.2 on Mac OS

**Comment by Wano-k** [comment]
Sorry, I quickly gave the code as an example and didn't test it. Here is something that worked for me:

```
function changeObject(MY_NEW_ID) {
    let portion = Core.Position.createFromVector3($object.position).getGlobalPortion();
    let portionDatas = Core.Game.current.getPortionDatas(Scene.Map.current.id, portion);
    let indexState = portionDatas.si.indexOf($object.id);
    if (indexState === -1) {
        indexState = portionDatas.si.length;
        portionDatas.si.push($object.id);
        portionDatas.s.push([1]);
    }
    EventCommand.ChangeState.removeAll(portionDatas, indexState);
    EventCommand.ChangeState.addState(portionDatas, indexState, MY_NEW_ID);
    $object.changeState();
}
changeObject(2);
```

**Comment by LucasMW** [comment]
It appears to work, thanks.

Something that I still wonder: You said that

> the object system can be more complicated than expected because of map portions where you need to register every state change in the map for saves purposes

What if I don't want to save the state change, but just run the script and change the state every time in runtime, every time the player loads that map, for example. There would be a simpler way to do it?

Thanks in advance!

**Comment by Wano-k** [comment]
Well it would be more complicated to do that since it wasn't designed that way. That would require to rewrite the beginning of  `changeState()` method. So it would just do something like:

```
this.currentState = this.system.states[i];
this.currentStateInstance = this.statesInstance[i];
```

where `i` is the index of state (not ID). It won't work if you do that just before `changeState()` because `changeState()` will erase these changes by checking map portions information.
